
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
    // Handle CORS preflight request
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders })
    }

    try {
        const { ph, temperature, bacteriaCount, predictedShelfLifeHours } = await req.json()

        const openAiKey = Deno.env.get('OPENAI_API_KEY')
        if (!openAiKey) {
            throw new Error('Missing OPENAI_API_KEY configuration')
        }

        const systemPrompt = `You are "Dairy Doctor", an expert AI food technologist for the Dairy Guard app. 
    Analyze the provided milk sensor data and give a concise, actionable recommendation in 2 sentences.
    Focus on safety, immediate actions (e.g., "Boil now"), and product suitability (e.g., "Good for Paneer").
    
    Context:
    - Safe pH: 6.6-6.8
    - Safe Temp: < 5°C
    - Bacteria limit: 200,000 CFU/ml
    `

        const userPrompt = `
      Current Sensor Data:
      - pH: ${ph}
      - Temperature: ${temperature}°C
      - Bacteria Count: ${bacteriaCount} CFU/ml
      - Predicted Shelf Life: ${predictedShelfLifeHours.toFixed(1)} hours
      
      What is your expert advice?
    `

        const response = await fetch('https://api.openai.com/v1/chat/completions', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${openAiKey}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                model: 'gpt-3.5-turbo',
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: userPrompt },
                ],
                max_tokens: 100,
                temperature: 0.7,
            }),
        })

        const data = await response.json()

        if (data.error) {
            console.error('OpenAI API Error:', data.error)
            throw new Error(`OpenAI Error: ${data.error.message || JSON.stringify(data.error)}`)
        }

        if (!data.choices || data.choices.length === 0) {
            throw new Error('No advice generated by AI (Empty response)')
        }

        const advice = data.choices[0].message.content

        return new Response(
            JSON.stringify({ advice }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
        )
    } catch (error) {
        return new Response(
            JSON.stringify({ error: error.message }),
            { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
        )
    }
})
